"""empty message

Revision ID: 69215db72b2b
Revises: b38389948e58
Create Date: 2025-04-09 22:54:16.574701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69215db72b2b'
down_revision = 'b38389948e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
